---
- name: add fish repository
  apt_repository:
    repo: ppa:fish-shell/release-3
  become: yes
  tags:
    - fish
    - fish-install
- name: install base utils
  apt:
    name: 'fish'
    update_cache: yes
    cache_valid_time: 3600
  become: yes
  tags:
    - fish
    - fish-install
- name: create symlinks for fish
  file:
    src: ~/.dotfiles/config/fish/config.fish
    dest: ~/.config/fish/config.fish
    state: link
  tags:
    - fish
    - fish-install
    - fish-symlink
